listen=YES
anonymous_enable=NO
local_enable=YES
write_enable=YES
local_umask=022
chroot_local_user=NO
pasv_enable=YES
pasv_min_port=40000
pasv_max_port=40010
pasv_address=127.0.0.1
local_root=/workspace
seccomp_sandbox=NO
