name: GitHub Profile Summary Cards

on:
  schedule:
    - cron: "* */24 * * *"
  workflow_dispatch:

permissions: 
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Clone repo
        uses: actions/checkout@v4
        
      - uses: vn7n24fzkq/github-profile-summary-cards@release
        with:
          USERNAME: ${{ github.repository_owner }}
          BRANCH_NAME: "output"
          UTC_OFFSET: 9 
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
