name: Waka Readme

on:
  schedule:
    - cron: "0 0 * * *"
  workflow_dispatch:

permissions:
  contents: write

jobs:
  update-readme:
    runs-on: ubuntu-latest

    steps:
      - uses: athul/waka-readme@master
        with:
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
          WAKATIME_API_KEY: ${{ secrets.WAKATIME_API_KEY }}
          SHOW_TITLE: true
          BLOCKS: "⬜🟧"
          TIME_RANGE: all_time
          LANG_COUNT: 10
          SHOW_TIME: true
          SHOW_TOTAL: true
          SHOW_MASKED_TIME: false
          STOP_AT_OTHER: true
          COMMIT_MESSAGE: "Updated waka-readme graph with new metrics"
          TARGET_PATH: "README.md"
          COMMITTER_NAME: "GitHub Action"
          COMMITTER_EMAIL: "41898282+github-actions[bot]@users.noreply.github.com"
